// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpWG3YAUEFJukiKDz2qfsyPoj-z8RccS8',
    appId: '1:541152085628:web:12ee82f45d14e20bbb6bf9',
    messagingSenderId: '541152085628',
    projectId: 'fir-meetup-24860',
    authDomain: 'fir-meetup-24860.firebaseapp.com',
    storageBucket: 'fir-meetup-24860.appspot.com',
    measurementId: 'G-19HRX6BPVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTbBYrHMezJtAudhhxBRo58p_bAvaY9_A',
    appId: '1:541152085628:android:139063b379bd9fabbb6bf9',
    messagingSenderId: '541152085628',
    projectId: 'fir-meetup-24860',
    storageBucket: 'fir-meetup-24860.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVGJ4gDZHFUiAXNhCqzAT0iLP1gQG_yko',
    appId: '1:541152085628:ios:ea8b55950fb2133abb6bf9',
    messagingSenderId: '541152085628',
    projectId: 'fir-meetup-24860',
    storageBucket: 'fir-meetup-24860.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVGJ4gDZHFUiAXNhCqzAT0iLP1gQG_yko',
    appId: '1:541152085628:ios:c581825530a48266bb6bf9',
    messagingSenderId: '541152085628',
    projectId: 'fir-meetup-24860',
    storageBucket: 'fir-meetup-24860.appspot.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
